version: '3.8'
services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v7.4.0
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-server-config
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./central-server-config:/central-server-config

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customerservice
      - MYSQL_USER=customerservice
      - MYSQL_PASSWORD=customerservice
    volumes:
      - mysql_data:/var/lib/mysql

  customerservice:
    build:
      context: ./customerservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/customerservice?useUnicode=true&characterEncoding=utf8
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://jhipster-registry:8761/eureka/
    depends_on:
      - mysql
      - jhipster-registry

  orderservice:
    build:
      context: ./orderservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orderservice?useUnicode=true&characterEncoding=utf8
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://jhipster-registry:8761/eureka/
    depends_on:
      - mysql
      - jhipster-registry

volumes:
  mysql_data: